spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kp-gaza
    username: user
    password: pwd
  jpa:
    show-sql: true
    open-in-view: false
    hibernate.ddl-auto: create
  cloud:
    consul:
      enabled: false

---
spring.profiles: docker

spring:
  application:
    name: money-distribution
  cloud:
    consul:
      discovery:
        instance-id: ${spring.application.name}.${random.value}
  datasource:
    url: jdbc:postgresql://postgresql:5432/kp-gaza
    username: user
    password: pwd
  jpa:
    show-sql: true
    open-in-view: false
    hibernate.ddl-auto: create

