spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    data: classpath:sql/data-h2.sql
  jpa:
    show-sql: true
    open-in-view: false
    hibernate.ddl-auto: create
  cloud:
    consul:
      enabled: false

springdoc:
  swagger-ui:
    url: https://raw.githubusercontent.com/HomoEfficio/kp-gaza/master/api-docs.yml

---
spring.profiles: docker

spring:
  application:
    name: money-distribution
  cloud:
    consul:
      enabled: true
      discovery:
        instance-id: ${spring.application.name}.${random.value}
  datasource:
    url: jdbc:postgresql://postgresql:5432/kp-gaza
    username: user
    password: pwd
  jpa:
    show-sql: true
    open-in-view: false
    hibernate.ddl-auto: update
