version: '2.4'

services:
  postgresql:
    image: postgres:12-alpine
    container_name: postgres
    networks:
      - my-network
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=kp-gaza
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pwd
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d kp-gaza"]
      interval: 20s
      timeout: 5s
      retries: 10
  money-distribution:
    build: money-distribution/
    mem_limit: 300m
    networks:
      - my-network
    depends_on:
      - postgresql
      - consul-server-2
  edge-server:
    build: edge-server/
    mem_limit: 200m
    networks:
      - my-network
    ports:
      - "9000:9000"
    depends_on:
      - consul-server-1
  consul-server-1:
    image: consul:latest
    container_name: consul-server-container-1
    entrypoint:
      - consul
      - agent
      - -server
      - -ui
      - -node=consul-server-node-1
      - -bootstrap-expect=3
      - -data-dir=/var/logs/consul
      - -client=0.0.0.0
    networks:
      my-network:
        aliases:
          - consul-server-nw-alias-1
    ports:
      - "8500:8500"
  consul-server-2:
    image: consul:latest
    container_name: consul-server-container-2
    entrypoint:
      - consul
      - agent
      - -server
      - -node=consul-server-node-2
      - -bootstrap-expect=3
      - -data-dir=/var/logs/consul
      - -retry-join=consul-server-1
      - -client=0.0.0.0
    networks:
      my-network:
        aliases:
          - consul-server-nw-alias-2
  consul-server-3:
    image: consul:latest
    container_name: consul-server-container-3
    entrypoint:
      - consul
      - agent
      - -server
      - -node=consul-server-node-3
      - -bootstrap-expect=3
      - -data-dir=/var/logs/consul
      - -retry-join=consul-server-1
      - -client=0.0.0.0
    networks:
      my-network:
        aliases:
          - consul-server-nw-alias-3

networks:
  my-network:
    name: my-network
