version: '2.4'

services:
  postgresql:
    image: postgres:12-alpine
    container_name: postgres
    networks:
      - my-network
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=kp-gaza
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pwd
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d kp-gaza"]
      interval: 20s
      timeout: 5s
      retries: 10
  money-distribution:
    build: money-distribution/
    mem_limit: 300m
    networks:
      - my-network
    depends_on:
      - postgresql
  edge-server:
    build: edge-server/
    mem_limit: 200m
    networks:
      - my-network
    ports:
      - "9000:9000"


networks:
  my-network:
    name: my-network
