server:
  port: 9000

spring:
  application:
    name: edge-server
  cloud:
    consul:
      discovery:
        instance-id: ${spring.application.name}.${random.value}
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      routes:
        - id: money-distribution
          uri: lb://money-distribution:${upstream.kp-gaza.port}/
          predicates:
            - Path=/**

upstream:
  kp-gaza:
    port: 8080

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  endpoint:
    health:
      show-details: always
